ha_dns_vip: ENC[AES256_GCM,data:f2hIzjutm8D0,iv:EhEDko7Mxp0SP2H5CxitN3oVuH2c9wUkLs9ZfJcCAKg=,tag:N/71FvzgA3LzrM6cQg0P7A==,type:str]
ha_dns_vip_cidr: ENC[AES256_GCM,data:4SaVA2GzzJpBQlx1,iv:2niLIoIK9S8IGw27DrO9VBcyURUxV0fgJcBymjyBMDw=,tag:f9xixezHAsGG86LO5dOU1A==,type:str]
ha_dns_vrid: ENC[AES256_GCM,data:Cpk=,iv:DgIusSRIRySaLIzODBA2ZklAwGG/gkHqQ6+jPtMSl/k=,tag:EXLhLIALx/1HdqFdoCZEYQ==,type:int]
# VRRP auth_pass
ha_dns_keepalived_auth_pass: ENC[AES256_GCM,data:i0Nzzxs5wba/3uJ8Zlpwz+jzLZmx16NlnFkpqZZ3J4k=,iv:5igpM58MfMzatMmTbrgmXrNXrQs0o6ztZEJIUrxMcxo=,tag:jm00GYtPJ4xhj7pYrrL/2Q==,type:str]
# Technitium web UI password
ha_dns_admin_password: ENC[AES256_GCM,data:1XH4nkc+36V4w//EgdcJWjf+5sLVRFT/9fFIbwtNkmI=,iv:To23NTUeMCCZ7HMXFwEZ9DiP67w1z9Ls+/k/SZ3U1Ls=,tag:Xy0T7g9ELgRSpaLF2Y2CLQ==,type:str]
sops:
    age:
        - recipient: age1trzalmfzy22xjj8mrdrgj4n063ve90wj049szwqa33slhny3hpnqr06t8u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQ1d4L2RDVXpVcXVSOVFh
            UndzeXFJV1lKMTh2RlZLL1pzWUxyWm9Nc1VRCklKb2p3VWtvSVZiNytGL0Voakoz
            eG9mV1F5c2RnczRDK1ZBTWhwYWFNV2MKLS0tIGNDSlVMcHpWQmptU0lPTlIzUTJT
            aFgydC82SnRvM3NzbllISzUyaCt1cG8KSoDdoLcVQCBplN+i/gEQXqH+x4m1iR6E
            IcKYeCoFRFLTcQ4XYeUUmDNZpHHs8EO9icj6wp7PtJ33IXERn7tgDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T16:03:18Z"
    mac: ENC[AES256_GCM,data:4/mGiNZA638WVWFb1Hp2jDACSXat7k36pcl2GW7GI3gbOn4Eb/9/TQc1z40kC9/koiU3XN1g7dDRwSk9Hc+Ltfw7f+qlsQ5JsKSpv6kJ18XNzt/j0alvJ7MY3K5+eD/paG7UR+sXNHgVuUPJ8VDSoxht1gqEgvoiZ+ge8/+xMKg=,iv:xrXuv+NfgIAcQ1l+u+L+1Kdv2BeGNUHTSINpdm2gs/o=,tag:0zTnd9/BJE2T77pENsh6eg==,type:str]
    encrypted_regex: .*
    version: 3.11.0
