all:
  hosts:
  children:
    kubernetes_cluster:
      hosts:
        bn-kube-01.int.bollingnet.net:
        bn-kube-02.int.bollingnet.net:
        bn-kube-03.int.bollingnet.net:
        bn-kube-04.int.bollingnet.net:
        bn-kube-05.int.bollingnet.net:
        bn-kube-06.int.bollingnet.net:
    docker:
      hosts:
        bn-docker-01.int.bollingnet.net:
        bn-docker-02.int.bollingnet.net:
        bn-docker-03.int.bollingnet.net:
    ha_dns:
      hosts:
        bn-docker-01.int.bollingnet.net:
        bn-docker-02.int.bollingnet.net:
    standalone_dns:
      hosts:
        bn-docker-03.int.bollingnet.net:
    dhcp_servers:
      hosts:
        bn-docker-01.int.bollingnet.net:
    proxmox:
      hosts:
        bn-prox-01.int.bollingnet.net:
        bn-prox-02.int.bollingnet.net:
    ups_monitors:
      hosts:
        bn-upsm-01.int.bollingnet.net:
        bn-upsm-02.int.bollingnet.net:
        bn-upsm-03.int.bollingnet.net:
